import React from 'react'
import {
  AlertCircle,
  AlertTriangle,
  Angry,
  Apple,
  BarChart2,
  Bell,
  BellOff,
  Bike,
  Bird,
  Bot,
  Bug,
  Car,
  Cat,
  Check,
  CheckCircle2,
  Cherry,
  Circle,
  Clock,
  Cloud,
  CloudRain,
  Code,
  Coffee,
  Cookie,
  Dog,
  Download,
  Dumbbell,
  Eye,
  File,
  FileCode,
  FileText,
  Fish,
  Flame,
  Flower,
  Folder,
  FolderOpen,
  Frown,
  Globe,
  Heart,
  HelpCircle,
  Info,
  Key,
  Laptop,
  Laugh,
  Layers,
  Leaf,
  Lightbulb,
  Link,
  ListChecks,
  Lock,
  Medal,
  Meh,
  Minus,
  Monitor,
  Moon,
  Mountain,
  Package,
  Pencil,
  Pin,
  Pizza,
  Plane,
  Plus,
  Rabbit,
  RefreshCw,
  Rocket,
  Save,
  Search,
  Send,
  Settings,
  Ship,
  Smile,
  SmilePlus,
  Snowflake,
  Sparkles,
  Star,
  Sun,
  Tag,
  Target,
  ThumbsDown,
  ThumbsUp,
  Train,
  Trash2,
  TrendingDown,
  TrendingUp,
  Trophy,
  Unlock,
  Upload,
  User,
  Users,
  Waves,
  Wind,
  Wrench,
  XCircle,
  Zap,
  type LucideIcon,
} from 'lucide-react'

// Specific per-emoji mappings. Lookup strips variation selectors first (see below).
const EMOJI_ICON_MAP: Record<string, LucideIcon> = {
  // Status / outcome
  '✅': CheckCircle2,
  '✔': Check,
  '❌': XCircle,
  '⚠': AlertTriangle,
  '🚨': AlertCircle,
  'ℹ': Info,
  '❓': HelpCircle,
  '❗': AlertCircle,
  '‼': AlertCircle,

  // Faces / emotion
  '😀': Smile,
  '😁': Laugh,
  '😂': Laugh,
  '🤣': Laugh,
  '😃': Smile,
  '😄': Laugh,
  '😅': SmilePlus,
  '😆': Laugh,
  '😇': Smile,
  '😈': Angry,
  '😉': Smile,
  '😊': Smile,
  '😋': Smile,
  '😌': Meh,
  '😍': Heart,
  '🥰': Heart,
  '😎': Smile,
  '🤓': Smile,
  '🧐': Search,
  '😏': Meh,
  '😑': Meh,
  '😒': Meh,
  '😓': Frown,
  '😔': Frown,
  '😕': Frown,
  '😖': Frown,
  '😗': Smile,
  '😘': Heart,
  '😙': Smile,
  '😚': Smile,
  '😛': Smile,
  '😜': Smile,
  '😝': Smile,
  '😞': Frown,
  '😟': Frown,
  '😠': Angry,
  '😡': Angry,
  '😢': Frown,
  '😣': Frown,
  '😤': Angry,
  '😥': Frown,
  '😦': Frown,
  '😧': Frown,
  '😨': AlertCircle,
  '😩': Frown,
  '😪': Frown,
  '😫': Frown,
  '😬': Meh,
  '😭': Frown,
  '😮': AlertCircle,
  '😯': AlertCircle,
  '😰': AlertCircle,
  '😱': AlertCircle,
  '😲': AlertCircle,
  '😳': AlertCircle,
  '😴': Moon,
  '😵': AlertCircle,
  '😶': Meh,
  '😷': Plus,
  '🤒': Frown,
  '🤕': Frown,
  '🤔': HelpCircle,
  '🤗': Smile,
  '🤙': ThumbsUp,
  '🤚': Meh,
  '🤛': ThumbsUp,
  '🤜': ThumbsUp,
  '🤝': Users,
  '🤞': Star,
  '🤟': Sparkles,
  '🤦': Frown,
  '🤧': Frown,
  '🤨': Meh,
  '🤩': Star,
  '🤪': Smile,
  '🤫': Meh,
  '🤬': Angry,
  '🤭': Smile,
  '🤮': Frown,
  '🤯': AlertCircle,
  '🥱': Moon,
  '🥲': Smile,
  '🥳': Sparkles,
  '🥴': Meh,
  '🥵': Flame,
  '🥶': Snowflake,
  '🥸': Smile,
  '🥹': Smile,
  '🫠': Meh,
  '🫡': Check,
  '🫢': AlertCircle,
  '🫣': Eye,
  '🫤': Meh,
  '🫥': Meh,
  '🫦': Smile,
  '🫧': Sparkles,
  '🫨': AlertCircle,
  '👋': Smile,
  '👌': Check,
  '👍': ThumbsUp,
  '👎': ThumbsDown,
  '👏': Star,
  '👐': Users,
  '👤': User,
  '👥': Users,
  '👀': Eye,
  '👁': Eye,
  '🫶': Heart,
  '🙌': Star,
  '🙏': Star,

  // Animals
  '🐶': Dog,
  '🐕': Dog,
  '🦮': Dog,
  '🐩': Dog,
  '🐱': Cat,
  '🐈': Cat,
  '🐭': Smile,
  '🐹': Rabbit,
  '🐰': Rabbit,
  '🐇': Rabbit,
  '🦊': Smile,
  '🐻': Smile,
  '🐼': Smile,
  '🐨': Smile,
  '🐯': Smile,
  '🦁': Smile,
  '🐮': Smile,
  '🐷': Smile,
  '🐸': Smile,
  '🐵': Smile,
  '🙈': Eye,
  '🙉': Bell,
  '🙊': Meh,
  '🐔': Bird,
  '🐧': Bird,
  '🐦': Bird,
  '🦅': Bird,
  '🦆': Bird,
  '🦉': Bird,
  '🦚': Bird,
  '🦜': Bird,
  '🐊': Smile,
  '🐢': Smile,
  '🦎': Smile,
  '🐍': AlertTriangle,
  '🐲': Flame,
  '🦕': Smile,
  '🦖': Smile,
  '🐳': Waves,
  '🐋': Waves,
  '🐬': Waves,
  '🦭': Waves,
  '🐟': Fish,
  '🐠': Fish,
  '🐡': Fish,
  '🦈': AlertTriangle,
  '🐙': Sparkles,
  '🦑': Sparkles,
  '🦐': Sparkles,
  '🦞': Sparkles,
  '🦀': Smile,
  '🐚': Sparkles,
  '🐌': Smile,
  '🦋': Sparkles,
  '🐛': Bug,
  '🐜': Bug,
  '🐝': Star,
  '🪲': Bug,
  '🪳': Bug,
  '🦟': AlertTriangle,
  '🦗': AlertTriangle,
  '🕷': AlertTriangle,
  '🦂': AlertTriangle,
  '🐾': Dog,

  // Nature / weather
  '🌱': Leaf,
  '🌿': Leaf,
  '☘': Leaf,
  '🍀': Leaf,
  '🍁': Leaf,
  '🍂': Leaf,
  '🍃': Leaf,
  '🌲': Mountain,
  '🌳': Mountain,
  '🌴': Mountain,
  '🌵': Mountain,
  '🪴': Flower,
  '🌾': Leaf,
  '🌺': Flower,
  '🌸': Flower,
  '🌼': Flower,
  '🌻': Sun,
  '🌹': Flower,
  '🥀': Flower,
  '💐': Flower,
  '🍄': Sparkles,
  '🪸': Waves,
  '🌊': Waves,
  '💧': Waves,
  '💦': Waves,
  '🌀': RefreshCw,
  '🌈': Sparkles,
  '⛅': Cloud,
  '🌤': Sun,
  '🌥': Cloud,
  '🌦': CloudRain,
  '🌧': CloudRain,
  '⛈': CloudRain,
  '🌩': Zap,
  '🌨': Snowflake,
  '❄': Snowflake,
  '☃': Snowflake,
  '⛄': Snowflake,
  '🌬': Wind,
  '🌪': Wind,
  '🌫': Cloud,
  '🌡': AlertCircle,
  '☀': Sun,
  '🌙': Moon,
  '🌛': Moon,
  '🌜': Moon,
  '🌝': Moon,
  '🌞': Sun,
  '🪐': Globe,
  '⭐': Star,
  '🌟': Star,
  '💫': Sparkles,
  '✨': Sparkles,
  '☄': Flame,
  '🌍': Globe,
  '🌎': Globe,
  '🌏': Globe,
  '🗺': Globe,
  '🧭': Target,
  '🏔': Mountain,
  '⛰': Mountain,
  '🌋': Mountain,
  '🗻': Mountain,
  '🏕': Mountain,
  '🏖': Waves,
  '🏜': Sun,
  '🏝': Waves,

  // Food & drink
  '🍕': Pizza,
  '🍔': Layers,
  '🍟': Layers,
  '🍗': Star,
  '🌮': Layers,
  '🌯': Layers,
  '🥙': Layers,
  '🥪': Layers,
  '🥚': Circle,
  '🍳': Flame,
  '🥞': Layers,
  '🧇': Layers,
  '🥓': Layers,
  '🥩': Layers,
  '🍖': Layers,
  '🍱': Package,
  '🍣': Layers,
  '🍜': Layers,
  '🍝': Layers,
  '🍛': Layers,
  '🍲': Layers,
  '🥗': Leaf,
  '🥘': Flame,
  '🫕': Flame,
  '🥫': Package,
  '🍿': Star,
  '🧂': Star,
  '🍦': Star,
  '🍧': Star,
  '🍨': Star,
  '🍩': Star,
  '🍪': Cookie,
  '🎂': Star,
  '🍰': Star,
  '🧁': Star,
  '🥧': Star,
  '🍫': Star,
  '🍬': Star,
  '🍭': Star,
  '🍮': Star,
  '🍯': Star,
  '🍎': Apple,
  '🍏': Apple,
  '🍐': Apple,
  '🍊': Cherry,
  '🍋': Cherry,
  '🍌': Cherry,
  '🍍': Cherry,
  '🥭': Cherry,
  '🍓': Cherry,
  '🫐': Cherry,
  '🍒': Cherry,
  '🍑': Cherry,
  '🥝': Cherry,
  '🍅': Cherry,
  '🫒': Leaf,
  '🥥': Cherry,
  '🫑': Leaf,
  '🥦': Leaf,
  '🥬': Leaf,
  '🥒': Leaf,
  '🌽': Leaf,
  '🥕': Leaf,
  '🧅': Leaf,
  '🧄': Leaf,
  '🥔': Leaf,
  '🍠': Leaf,
  '☕': Coffee,
  '🫖': Coffee,
  '🍵': Coffee,
  '🧋': Coffee,
  '🍺': Star,
  '🍻': Star,
  '🥂': Star,
  '🍷': Star,
  '🍸': Star,
  '🍹': Star,
  '🧃': Coffee,
  '🥤': Coffee,
  '🫗': Coffee,
  '🫙': Package,
  '🍶': Coffee,

  // Travel & transport
  '🚀': Rocket,
  '✈': Plane,
  '🛫': Plane,
  '🛬': Plane,
  '🛩': Plane,
  '💺': Plane,
  '🚁': Plane,
  '🛸': Rocket,
  '🚂': Train,
  '🚆': Train,
  '🚇': Train,
  '🚊': Train,
  '🚉': Train,
  '🚃': Train,
  '🚋': Train,
  '🚝': Train,
  '🚄': Train,
  '🚅': Train,
  '🚈': Train,
  '🚞': Train,
  '🚌': Car,
  '🚎': Car,
  '🏎': Car,
  '🚑': Plus,
  '🚒': Flame,
  '🚓': AlertCircle,
  '🚕': Car,
  '🚗': Car,
  '🚙': Car,
  '🛻': Car,
  '🚚': Package,
  '🚛': Package,
  '🚜': Wrench,
  '🏍': Bike,
  '🛵': Bike,
  '🚲': Bike,
  '🛴': Bike,
  '🛹': Bike,
  '🛼': Bike,
  '🚶': User,
  '🧍': User,
  '🧎': User,
  '🏃': User,
  '⛵': Ship,
  '🚤': Ship,
  '🛥': Ship,
  '🛳': Ship,
  '⛴': Ship,
  '🚢': Ship,
  '🗼': Mountain,
  '🗽': Star,
  '⛪': Mountain,
  '🏯': Mountain,
  '🏰': Mountain,
  '🏟': Target,
  '🏠': Folder,
  '🏡': Folder,
  '🏢': Layers,
  '🏣': Layers,
  '🏤': Layers,
  '🏥': Plus,
  '🏦': Tag,
  '🏨': Layers,
  '🏩': Heart,
  '🏪': Tag,
  '🏫': Layers,
  '🏬': Layers,
  '🏭': Settings,
  '🌆': Sun,
  '🌇': Sun,
  '🌃': Moon,
  '🌉': Moon,
  '🌁': Cloud,
  '🎡': Sparkles,
  '🎢': Sparkles,
  '🎠': Sparkles,

  // Tools / dev
  '🔧': Wrench,
  '🛠': Settings,
  '⚙': Settings,
  '💻': Laptop,
  '🖥': Monitor,
  '📟': Monitor,
  '🖱': Monitor,
  '⌨': Code,
  '🖨': Monitor,
  '📠': Send,
  '📺': Monitor,
  '📷': Eye,
  '📸': Eye,
  '📹': Eye,
  '🎥': Eye,
  '📼': Save,
  '📽': Eye,
  '🎞': Eye,
  '📞': Send,
  '☎': Send,
  '📲': Send,
  '📱': Laptop,
  '🔋': Zap,
  '🪫': AlertTriangle,
  '🔌': Zap,
  '💡': Lightbulb,

  // Files / docs
  '📝': FileText,
  '📄': File,
  '📃': FileText,
  '📋': ListChecks,
  '📁': Folder,
  '📂': FolderOpen,
  '🗂': Layers,
  '💾': Save,
  '📑': FileCode,
  '📜': FileText,
  '📓': FileText,
  '📔': FileText,
  '📒': FileText,
  '📕': FileText,
  '📗': FileText,
  '📘': FileText,
  '📙': FileText,
  '📚': Layers,
  '🗞': FileText,
  '📰': FileText,
  '📇': Tag,
  '📆': Clock,
  '📅': Clock,
  '🗓': Clock,
  '📊': BarChart2,
  '📈': TrendingUp,
  '📉': TrendingDown,

  // Communication
  '💬': Bot,
  '💭': HelpCircle,
  '🗨': Bot,
  '🗯': AlertCircle,
  '📢': Bell,
  '📣': Bell,
  '🔔': Bell,
  '🔕': BellOff,
  '📧': Send,
  '📨': Send,
  '📩': Send,
  '📤': Upload,
  '📥': Download,
  '📮': Send,
  '📫': Send,
  '📪': Send,
  '📬': Send,
  '📭': Send,

  // Ideas / creative
  '🎯': Target,
  '⚡': Zap,
  '🔥': Flame,
  '🎉': Sparkles,
  '🏆': Trophy,
  '🥇': Medal,
  '🥈': Medal,
  '🥉': Medal,
  '🎖': Medal,
  '🏅': Medal,
  '🎗': Tag,
  '🎫': Tag,
  '🎪': Sparkles,
  '🎭': Sparkles,
  '🎨': Sparkles,
  '🖼': Eye,
  '🎬': Eye,
  '🎤': Smile,
  '🎧': Smile,
  '🎵': Smile,
  '🎶': Smile,
  '🎸': Smile,
  '🎹': Smile,
  '🎺': Smile,
  '🎻': Smile,
  '🥁': Smile,
  '🪘': Smile,
  '🎮': Laptop,
  '🕹': Laptop,
  '🎲': Sparkles,
  '🧸': Smile,

  // Data / analytics
  '🔍': Search,
  '🔎': Search,
  '🔭': Search,
  '🔬': Search,
  '🧪': Flame,
  '🧫': Sparkles,
  '🧬': Sparkles,

  // Security
  '🔒': Lock,
  '🔓': Unlock,
  '🛡': Lock,
  '🔑': Key,
  '🗝': Key,
  '🔐': Lock,

  // Package / deploy
  '📦': Package,
  '🏷': Tag,
  '📌': Pin,
  '📍': Pin,
  '🎁': Package,
  '🛒': Package,
  '🧳': Package,

  // Actions
  '🔄': RefreshCw,
  '✏': Pencil,
  '🗑': Trash2,
  '➕': Plus,
  '➖': Minus,
  '⬆': Upload,
  '⬇': Download,
  '🔗': Link,
  '🌐': Globe,
  '📡': Globe,

  // Time
  '⏰': Clock,
  '🕐': Clock,
  '⏱': Clock,
  '⏳': Clock,

  // Sports / fitness
  '⚽': Target,
  '🏀': Target,
  '🏈': Target,
  '⚾': Target,
  '🥎': Target,
  '🏐': Target,
  '🏉': Target,
  '🥏': Target,
  '🎾': Target,
  '🏸': Target,
  '🏒': Target,
  '🏓': Target,
  '🥊': Target,
  '🥋': Target,
  '🤼': Users,
  '🤸': User,
  '⛹': User,
  '🤺': User,
  '🏊': Waves,
  '🚴': Bike,
  '🏋': Dumbbell,
  '🤾': User,
  '🧘': User,
  '🧗': Mountain,
  '🧜': Waves,
  '🧚': Sparkles,
  '🧝': Sparkles,
  '🧙': Sparkles,
  '🧛': Sparkles,
  '🧟': AlertCircle,
  '🏇': Smile,
  '⛷': Mountain,
  '🏂': Mountain,
  '🏹': Target,
  '🎿': Mountain,
  '🛷': Mountain,
  '🥌': Target,

  // Hearts / symbols
  '❤': Heart,
  '🧡': Heart,
  '💛': Heart,
  '💚': Heart,
  '💙': Heart,
  '💜': Heart,
  '🖤': Heart,
  '🤍': Heart,
  '🤎': Heart,
  '💔': Heart,
  '❣': Heart,
  '💕': Heart,
  '💞': Heart,
  '💓': Heart,
  '💗': Heart,
  '💖': Heart,
  '💘': Heart,
  '💝': Heart,
  '💟': Heart,
  '☮': Circle,
  '✡': Star,
  '☸': RefreshCw,
  '✝': Plus,
  '☦': Plus,
  '☯': RefreshCw,
  '🕉': Star,
  '⚛': Zap,
  '🛐': Star,
  '💲': Tag,
  '💱': RefreshCw,
  '©': Circle,
  '®': Circle,
  '™': Circle,

  // Misc objects
  '🎓': Lightbulb,
  '🧩': Layers,
  '🔮': Sparkles,
  '💎': Sparkles,
  '🧠': Lightbulb,
  '💰': Tag,
  '🏗': Layers,
  '🪛': Wrench,
  '🪝': Link,
  '🪜': Layers,
  '🧰': Wrench,
  '🧲': Target,
  '🔩': Settings,
  '🧾': FileText,
  '💳': Tag,
  '🗿': Mountain,
  '🧿': Eye,
  '🪬': Eye,
  '💈': AlertCircle,
  '🪞': Eye,
  '🪟': Eye,
  '🛋': Layers,
  '🛏': Moon,
  '🚪': Folder,
  '🪑': Layers,
  '🚽': Layers,
  '🪠': Wrench,
  '🚿': Waves,
  '🛁': Waves,
  '🧴': Package,
  '🧷': Pin,
  '🧹': Wrench,
  '🧺': Package,
  '🧻': FileText,
  '🧼': Waves,
  '🪣': Package,
  '🧽': Wrench,
  '🪒': Wrench,
  '🪮': Wrench,
}

// Comprehensive Unicode emoji regex that matches all emoji sequences:
// - Extended pictographic (covers most emoji ranges) with optional variation selector + skin tone
// - ZWJ sequences (family/couple emoji joined by U+200D)
// - Regional indicator pairs (flag emoji)
// - Keycap sequences (#, *, 0-9 + FE0F + 20E3)
const ANY_EMOJI_REGEX =
  /\p{Extended_Pictographic}(?:\uFE0F|\uFE0E)?(?:[\u{1F3FB}-\u{1F3FF}])?(?:\u200D(?:\p{Extended_Pictographic}|\uFE0F)(?:[\u{1F3FB}-\u{1F3FF}])?)*|\p{Regional_Indicator}{2}|[#*0-9]\uFE0F\u20E3/gu

// Fallback icon for any emoji not in the specific map
const FALLBACK_ICON = Circle

/**
 * Normalise an emoji match for map lookup: strip variation selectors and
 * keycap combining marks so e.g. "⚠️" (with U+FE0F) looks up as "⚠".
 */
function normaliseEmoji(emoji: string): string {
  return emoji.replace(/[\uFE0F\uFE0E\u20E3]/g, '')
}

/**
 * Splits a string into React nodes, replacing every emoji with an inline
 * Lucide icon. Emojis in the specific map get their mapped icon; everything
 * else gets a small generic circle.
 */
export function renderWithIcons(text: string, key?: string | number): React.ReactNode {
  const parts: Array<string | React.ReactElement> = []
  let lastIndex = 0

  // Reset stateful regex before each call
  ANY_EMOJI_REGEX.lastIndex = 0

  let match: RegExpExecArray | null
  while ((match = ANY_EMOJI_REGEX.exec(text)) !== null) {
    const emoji = match[0]
    const index = match.index

    if (index > lastIndex) {
      parts.push(text.slice(lastIndex, index))
    }

    const normalised = normaliseEmoji(emoji)
    const Icon =
      EMOJI_ICON_MAP[emoji] ?? EMOJI_ICON_MAP[normalised] ?? FALLBACK_ICON

    parts.push(
      <Icon
        key={`${key ?? ''}-emoji-${index}`}
        aria-label={emoji}
        className={
          Icon === FALLBACK_ICON
            ? 'inline-block h-[0.6em] w-[0.6em] align-middle mx-[0.15em] flex-shrink-0 opacity-30 fill-current'
            : 'inline-block h-[1em] w-[1em] align-[-0.125em] mx-[0.1em] flex-shrink-0'
        }
      />,
    )

    lastIndex = index + emoji.length
  }

  if (lastIndex < text.length) {
    parts.push(text.slice(lastIndex))
  }

  if (parts.length === 0) return text
  if (parts.length === 1 && typeof parts[0] === 'string') return parts[0]

  return <>{parts}</>
}

/**
 * Walks React children and replaces emoji strings in text nodes with icons.
 * Safe to use inside markdown component renderers.
 */
export function processChildrenWithIcons(
  children: React.ReactNode,
  keyPrefix?: string,
): React.ReactNode {
  return React.Children.map(children, (child, i) => {
    if (typeof child === 'string') {
      return renderWithIcons(child, `${keyPrefix ?? ''}-${i}`)
    }
    return child
  })
}
