import React from 'react'
import {
  WarningCircle,
  Warning,
  SmileyAngry,
  AppleLogo,
  ChartBar,
  Bell,
  BellSlash,
  Bicycle,
  Bird,
  Robot,
  Bug,
  Car,
  Cat,
  Check,
  CheckCircle,
  Cherries,
  Circle,
  Clock,
  Cloud,
  CloudRain,
  Code,
  Coffee,
  Cookie,
  Dog,
  DownloadSimple,
  Barbell,
  Eye,
  File,
  FileCode,
  FileText,
  Fish,
  Flame,
  Flower,
  Folder,
  FolderOpen,
  SmileySad,
  Globe,
  Heart,
  Question,
  Info,
  Key,
  Laptop,
  SmileyWink,
  Stack,
  Leaf,
  Lightbulb,
  Link,
  ListChecks,
  Lock,
  Medal,
  SmileyMeh,
  Minus,
  Monitor,
  Moon,
  Mountains,
  Package,
  Pencil,
  PushPin,
  Pizza,
  Airplane,
  Plus,
  Rabbit,
  ArrowsClockwise,
  Rocket,
  FloppyDisk,
  MagnifyingGlass,
  PaperPlaneTilt,
  Gear,
  Boat,
  Smiley,
  SmileySticker,
  Snowflake,
  ShootingStar,
  Star,
  Sun,
  Tag,
  Target,
  ThumbsDown,
  ThumbsUp,
  Train,
  Trash,
  TrendDown,
  TrendUp,
  Trophy,
  LockOpen,
  UploadSimple,
  User,
  Users,
  Waves,
  Wind,
  Wrench,
  XCircle,
  Lightning,
  type Icon,
} from '@phosphor-icons/react'

// Specific per-emoji mappings. Lookup strips variation selectors first (see below).
const EMOJI_ICON_MAP: Record<string, Icon> = {
  // Status / outcome
  '✅': CheckCircle,
  '✔': Check,
  '❌': XCircle,
  '⚠': Warning,
  '🚨': WarningCircle,
  'ℹ': Info,
  '❓': Question,
  '❗': WarningCircle,
  '‼': WarningCircle,

  // Faces / emotion
  '😀': Smiley,
  '😁': SmileyWink,
  '😂': SmileyWink,
  '🤣': SmileyWink,
  '😃': Smiley,
  '😄': SmileyWink,
  '😅': SmileySticker,
  '😆': SmileyWink,
  '😇': Smiley,
  '😈': SmileyAngry,
  '😉': Smiley,
  '😊': Smiley,
  '😋': Smiley,
  '😌': SmileyMeh,
  '😍': Heart,
  '🥰': Heart,
  '😎': Smiley,
  '🤓': Smiley,
  '🧐': MagnifyingGlass,
  '😏': SmileyMeh,
  '😑': SmileyMeh,
  '😒': SmileyMeh,
  '😓': SmileySad,
  '😔': SmileySad,
  '😕': SmileySad,
  '😖': SmileySad,
  '😗': Smiley,
  '😘': Heart,
  '😙': Smiley,
  '😚': Smiley,
  '😛': Smiley,
  '😜': Smiley,
  '😝': Smiley,
  '😞': SmileySad,
  '😟': SmileySad,
  '😠': SmileyAngry,
  '😡': SmileyAngry,
  '😢': SmileySad,
  '😣': SmileySad,
  '😤': SmileyAngry,
  '😥': SmileySad,
  '😦': SmileySad,
  '😧': SmileySad,
  '😨': WarningCircle,
  '😩': SmileySad,
  '😪': SmileySad,
  '😫': SmileySad,
  '😬': SmileyMeh,
  '😭': SmileySad,
  '😮': WarningCircle,
  '😯': WarningCircle,
  '😰': WarningCircle,
  '😱': WarningCircle,
  '😲': WarningCircle,
  '😳': WarningCircle,
  '😴': Moon,
  '😵': WarningCircle,
  '😶': SmileyMeh,
  '😷': Plus,
  '🤒': SmileySad,
  '🤕': SmileySad,
  '🤔': Question,
  '🤗': Smiley,
  '🤙': ThumbsUp,
  '🤚': SmileyMeh,
  '🤛': ThumbsUp,
  '🤜': ThumbsUp,
  '🤝': Users,
  '🤞': Star,
  '🤟': ShootingStar,
  '🤦': SmileySad,
  '🤧': SmileySad,
  '🤨': SmileyMeh,
  '🤩': Star,
  '🤪': Smiley,
  '🤫': SmileyMeh,
  '🤬': SmileyAngry,
  '🤭': Smiley,
  '🤮': SmileySad,
  '🤯': WarningCircle,
  '🥱': Moon,
  '🥲': Smiley,
  '🥳': ShootingStar,
  '🥴': SmileyMeh,
  '🥵': Flame,
  '🥶': Snowflake,
  '🥸': Smiley,
  '🥹': Smiley,
  '🫠': SmileyMeh,
  '🫡': Check,
  '🫢': WarningCircle,
  '🫣': Eye,
  '🫤': SmileyMeh,
  '🫥': SmileyMeh,
  '🫦': Smiley,
  '🫧': ShootingStar,
  '🫨': WarningCircle,
  '👋': Smiley,
  '👌': Check,
  '👍': ThumbsUp,
  '👎': ThumbsDown,
  '👏': Star,
  '👐': Users,
  '👤': User,
  '👥': Users,
  '👀': Eye,
  '👁': Eye,
  '🫶': Heart,
  '🙌': Star,
  '🙏': Star,

  // Animals
  '🐶': Dog,
  '🐕': Dog,
  '🦮': Dog,
  '🐩': Dog,
  '🐱': Cat,
  '🐈': Cat,
  '🐭': Smiley,
  '🐹': Rabbit,
  '🐰': Rabbit,
  '🐇': Rabbit,
  '🦊': Smiley,
  '🐻': Smiley,
  '🐼': Smiley,
  '🐨': Smiley,
  '🐯': Smiley,
  '🦁': Smiley,
  '🐮': Smiley,
  '🐷': Smiley,
  '🐸': Smiley,
  '🐵': Smiley,
  '🙈': Eye,
  '🙉': Bell,
  '🙊': SmileyMeh,
  '🐔': Bird,
  '🐧': Bird,
  '🐦': Bird,
  '🦅': Bird,
  '🦆': Bird,
  '🦉': Bird,
  '🦚': Bird,
  '🦜': Bird,
  '🐊': Smiley,
  '🐢': Smiley,
  '🦎': Smiley,
  '🐍': Warning,
  '🐲': Flame,
  '🦕': Smiley,
  '🦖': Smiley,
  '🐳': Waves,
  '🐋': Waves,
  '🐬': Waves,
  '🦭': Waves,
  '🐟': Fish,
  '🐠': Fish,
  '🐡': Fish,
  '🦈': Warning,
  '🐙': ShootingStar,
  '🦑': ShootingStar,
  '🦐': ShootingStar,
  '🦞': ShootingStar,
  '🦀': Smiley,
  '🐚': ShootingStar,
  '🐌': Smiley,
  '🦋': ShootingStar,
  '🐛': Bug,
  '🐜': Bug,
  '🐝': Star,
  '🪲': Bug,
  '🪳': Bug,
  '🦟': Warning,
  '🦗': Warning,
  '🕷': Warning,
  '🦂': Warning,
  '🐾': Dog,

  // Nature / weather
  '🌱': Leaf,
  '🌿': Leaf,
  '☘': Leaf,
  '🍀': Leaf,
  '🍁': Leaf,
  '🍂': Leaf,
  '🍃': Leaf,
  '🌲': Mountains,
  '🌳': Mountains,
  '🌴': Mountains,
  '🌵': Mountains,
  '🪴': Flower,
  '🌾': Leaf,
  '🌺': Flower,
  '🌸': Flower,
  '🌼': Flower,
  '🌻': Sun,
  '🌹': Flower,
  '🥀': Flower,
  '💐': Flower,
  '🍄': ShootingStar,
  '🪸': Waves,
  '🌊': Waves,
  '💧': Waves,
  '💦': Waves,
  '🌀': ArrowsClockwise,
  '🌈': ShootingStar,
  '⛅': Cloud,
  '🌤': Sun,
  '🌥': Cloud,
  '🌦': CloudRain,
  '🌧': CloudRain,
  '⛈': CloudRain,
  '🌩': Lightning,
  '🌨': Snowflake,
  '❄': Snowflake,
  '☃': Snowflake,
  '⛄': Snowflake,
  '🌬': Wind,
  '🌪': Wind,
  '🌫': Cloud,
  '🌡': WarningCircle,
  '☀': Sun,
  '🌙': Moon,
  '🌛': Moon,
  '🌜': Moon,
  '🌝': Moon,
  '🌞': Sun,
  '🪐': Globe,
  '⭐': Star,
  '🌟': Star,
  '💫': ShootingStar,
  '✨': ShootingStar,
  '☄': Flame,
  '🌍': Globe,
  '🌎': Globe,
  '🌏': Globe,
  '🗺': Globe,
  '🧭': Target,
  '🏔': Mountains,
  '⛰': Mountains,
  '🌋': Mountains,
  '🗻': Mountains,
  '🏕': Mountains,
  '🏖': Waves,
  '🏜': Sun,
  '🏝': Waves,

  // Food & drink
  '🍕': Pizza,
  '🍔': Stack,
  '🍟': Stack,
  '🍗': Star,
  '🌮': Stack,
  '🌯': Stack,
  '🥙': Stack,
  '🥪': Stack,
  '🥚': Circle,
  '🍳': Flame,
  '🥞': Stack,
  '🧇': Stack,
  '🥓': Stack,
  '🥩': Stack,
  '🍖': Stack,
  '🍱': Package,
  '🍣': Stack,
  '🍜': Stack,
  '🍝': Stack,
  '🍛': Stack,
  '🍲': Stack,
  '🥗': Leaf,
  '🥘': Flame,
  '🫕': Flame,
  '🥫': Package,
  '🍿': Star,
  '🧂': Star,
  '🍦': Star,
  '🍧': Star,
  '🍨': Star,
  '🍩': Star,
  '🍪': Cookie,
  '🎂': Star,
  '🍰': Star,
  '🧁': Star,
  '🥧': Star,
  '🍫': Star,
  '🍬': Star,
  '🍭': Star,
  '🍮': Star,
  '🍯': Star,
  '🍎': AppleLogo,
  '🍏': AppleLogo,
  '🍐': AppleLogo,
  '🍊': Cherries,
  '🍋': Cherries,
  '🍌': Cherries,
  '🍍': Cherries,
  '🥭': Cherries,
  '🍓': Cherries,
  '🫐': Cherries,
  '🍒': Cherries,
  '🍑': Cherries,
  '🥝': Cherries,
  '🍅': Cherries,
  '🫒': Leaf,
  '🥥': Cherries,
  '🫑': Leaf,
  '🥦': Leaf,
  '🥬': Leaf,
  '🥒': Leaf,
  '🌽': Leaf,
  '🥕': Leaf,
  '🧅': Leaf,
  '🧄': Leaf,
  '🥔': Leaf,
  '🍠': Leaf,
  '☕': Coffee,
  '🫖': Coffee,
  '🍵': Coffee,
  '🧋': Coffee,
  '🍺': Star,
  '🍻': Star,
  '🥂': Star,
  '🍷': Star,
  '🍸': Star,
  '🍹': Star,
  '🧃': Coffee,
  '🥤': Coffee,
  '🫗': Coffee,
  '🫙': Package,
  '🍶': Coffee,

  // Travel & transport
  '🚀': Rocket,
  '✈': Airplane,
  '🛫': Airplane,
  '🛬': Airplane,
  '🛩': Airplane,
  '💺': Airplane,
  '🚁': Airplane,
  '🛸': Rocket,
  '🚂': Train,
  '🚆': Train,
  '🚇': Train,
  '🚊': Train,
  '🚉': Train,
  '🚃': Train,
  '🚋': Train,
  '🚝': Train,
  '🚄': Train,
  '🚅': Train,
  '🚈': Train,
  '🚞': Train,
  '🚌': Car,
  '🚎': Car,
  '🏎': Car,
  '🚑': Plus,
  '🚒': Flame,
  '🚓': WarningCircle,
  '🚕': Car,
  '🚗': Car,
  '🚙': Car,
  '🛻': Car,
  '🚚': Package,
  '🚛': Package,
  '🚜': Wrench,
  '🏍': Bicycle,
  '🛵': Bicycle,
  '🚲': Bicycle,
  '🛴': Bicycle,
  '🛹': Bicycle,
  '🛼': Bicycle,
  '🚶': User,
  '🧍': User,
  '🧎': User,
  '🏃': User,
  '⛵': Boat,
  '🚤': Boat,
  '🛥': Boat,
  '🛳': Boat,
  '⛴': Boat,
  '🚢': Boat,
  '🗼': Mountains,
  '🗽': Star,
  '⛪': Mountains,
  '🏯': Mountains,
  '🏰': Mountains,
  '🏟': Target,
  '🏠': Folder,
  '🏡': Folder,
  '🏢': Stack,
  '🏣': Stack,
  '🏤': Stack,
  '🏥': Plus,
  '🏦': Tag,
  '🏨': Stack,
  '🏩': Heart,
  '🏪': Tag,
  '🏫': Stack,
  '🏬': Stack,
  '🏭': Gear,
  '🌆': Sun,
  '🌇': Sun,
  '🌃': Moon,
  '🌉': Moon,
  '🌁': Cloud,
  '🎡': ShootingStar,
  '🎢': ShootingStar,
  '🎠': ShootingStar,

  // Tools / dev
  '🔧': Wrench,
  '🛠': Gear,
  '⚙': Gear,
  '💻': Laptop,
  '🖥': Monitor,
  '📟': Monitor,
  '🖱': Monitor,
  '⌨': Code,
  '🖨': Monitor,
  '📠': PaperPlaneTilt,
  '📺': Monitor,
  '📷': Eye,
  '📸': Eye,
  '📹': Eye,
  '🎥': Eye,
  '📼': FloppyDisk,
  '📽': Eye,
  '🎞': Eye,
  '📞': PaperPlaneTilt,
  '☎': PaperPlaneTilt,
  '📲': PaperPlaneTilt,
  '📱': Laptop,
  '🔋': Lightning,
  '🪫': Warning,
  '🔌': Lightning,
  '💡': Lightbulb,

  // Files / docs
  '📝': FileText,
  '📄': File,
  '📃': FileText,
  '📋': ListChecks,
  '📁': Folder,
  '📂': FolderOpen,
  '🗂': Stack,
  '💾': FloppyDisk,
  '📑': FileCode,
  '📜': FileText,
  '📓': FileText,
  '📔': FileText,
  '📒': FileText,
  '📕': FileText,
  '📗': FileText,
  '📘': FileText,
  '📙': FileText,
  '📚': Stack,
  '🗞': FileText,
  '📰': FileText,
  '📇': Tag,
  '📆': Clock,
  '📅': Clock,
  '🗓': Clock,
  '📊': ChartBar,
  '📈': TrendUp,
  '📉': TrendDown,

  // Communication
  '💬': Robot,
  '💭': Question,
  '🗨': Robot,
  '🗯': WarningCircle,
  '📢': Bell,
  '📣': Bell,
  '🔔': Bell,
  '🔕': BellSlash,
  '📧': PaperPlaneTilt,
  '📨': PaperPlaneTilt,
  '📩': PaperPlaneTilt,
  '📤': UploadSimple,
  '📥': DownloadSimple,
  '📮': PaperPlaneTilt,
  '📫': PaperPlaneTilt,
  '📪': PaperPlaneTilt,
  '📬': PaperPlaneTilt,
  '📭': PaperPlaneTilt,

  // Ideas / creative
  '🎯': Target,
  '⚡': Lightning,
  '🔥': Flame,
  '🎉': ShootingStar,
  '🏆': Trophy,
  '🥇': Medal,
  '🥈': Medal,
  '🥉': Medal,
  '🎖': Medal,
  '🏅': Medal,
  '🎗': Tag,
  '🎫': Tag,
  '🎪': ShootingStar,
  '🎭': ShootingStar,
  '🎨': ShootingStar,
  '🖼': Eye,
  '🎬': Eye,
  '🎤': Smiley,
  '🎧': Smiley,
  '🎵': Smiley,
  '🎶': Smiley,
  '🎸': Smiley,
  '🎹': Smiley,
  '🎺': Smiley,
  '🎻': Smiley,
  '🥁': Smiley,
  '🪘': Smiley,
  '🎮': Laptop,
  '🕹': Laptop,
  '🎲': ShootingStar,
  '🧸': Smiley,

  // Data / analytics
  '🔍': MagnifyingGlass,
  '🔎': MagnifyingGlass,
  '🔭': MagnifyingGlass,
  '🔬': MagnifyingGlass,
  '🧪': Flame,
  '🧫': ShootingStar,
  '🧬': ShootingStar,

  // Security
  '🔒': Lock,
  '🔓': LockOpen,
  '🛡': Lock,
  '🔑': Key,
  '🗝': Key,
  '🔐': Lock,

  // Package / deploy
  '📦': Package,
  '🏷': Tag,
  '📌': PushPin,
  '📍': PushPin,
  '🎁': Package,
  '🛒': Package,
  '🧳': Package,

  // Actions
  '🔄': ArrowsClockwise,
  '✏': Pencil,
  '🗑': Trash,
  '➕': Plus,
  '➖': Minus,
  '⬆': UploadSimple,
  '⬇': DownloadSimple,
  '🔗': Link,
  '🌐': Globe,
  '📡': Globe,

  // Time
  '⏰': Clock,
  '🕐': Clock,
  '⏱': Clock,
  '⏳': Clock,

  // Sports / fitness
  '⚽': Target,
  '🏀': Target,
  '🏈': Target,
  '⚾': Target,
  '🥎': Target,
  '🏐': Target,
  '🏉': Target,
  '🥏': Target,
  '🎾': Target,
  '🏸': Target,
  '🏒': Target,
  '🏓': Target,
  '🥊': Target,
  '🥋': Target,
  '🤼': Users,
  '🤸': User,
  '⛹': User,
  '🤺': User,
  '🏊': Waves,
  '🚴': Bicycle,
  '🏋': Barbell,
  '🤾': User,
  '🧘': User,
  '🧗': Mountains,
  '🧜': Waves,
  '🧚': ShootingStar,
  '🧝': ShootingStar,
  '🧙': ShootingStar,
  '🧛': ShootingStar,
  '🧟': WarningCircle,
  '🏇': Smiley,
  '⛷': Mountains,
  '🏂': Mountains,
  '🏹': Target,
  '🎿': Mountains,
  '🛷': Mountains,
  '🥌': Target,

  // Hearts / symbols
  '❤': Heart,
  '🧡': Heart,
  '💛': Heart,
  '💚': Heart,
  '💙': Heart,
  '💜': Heart,
  '🖤': Heart,
  '🤍': Heart,
  '🤎': Heart,
  '💔': Heart,
  '❣': Heart,
  '💕': Heart,
  '💞': Heart,
  '💓': Heart,
  '💗': Heart,
  '💖': Heart,
  '💘': Heart,
  '💝': Heart,
  '💟': Heart,
  '☮': Circle,
  '✡': Star,
  '☸': ArrowsClockwise,
  '✝': Plus,
  '☦': Plus,
  '☯': ArrowsClockwise,
  '🕉': Star,
  '⚛': Lightning,
  '🛐': Star,
  '💲': Tag,
  '💱': ArrowsClockwise,
  '©': Circle,
  '®': Circle,
  '™': Circle,

  // Misc objects
  '🎓': Lightbulb,
  '🧩': Stack,
  '🔮': ShootingStar,
  '💎': ShootingStar,
  '🧠': Lightbulb,
  '💰': Tag,
  '🏗': Stack,
  '🪛': Wrench,
  '🪝': Link,
  '🪜': Stack,
  '🧰': Wrench,
  '🧲': Target,
  '🔩': Gear,
  '🧾': FileText,
  '💳': Tag,
  '🗿': Mountains,
  '🧿': Eye,
  '🪬': Eye,
  '💈': WarningCircle,
  '🪞': Eye,
  '🪟': Eye,
  '🛋': Stack,
  '🛏': Moon,
  '🚪': Folder,
  '🪑': Stack,
  '🚽': Stack,
  '🪠': Wrench,
  '🚿': Waves,
  '🛁': Waves,
  '🧴': Package,
  '🧷': PushPin,
  '🧹': Wrench,
  '🧺': Package,
  '🧻': FileText,
  '🧼': Waves,
  '🪣': Package,
  '🧽': Wrench,
  '🪒': Wrench,
  '🪮': Wrench,
}

// Comprehensive Unicode emoji regex that matches all emoji sequences:
// - Extended pictographic (covers most emoji ranges) with optional variation selector + skin tone
// - ZWJ sequences (family/couple emoji joined by U+200D)
// - Regional indicator pairs (flag emoji)
// - Keycap sequences (#, *, 0-9 + FE0F + 20E3)
const ANY_EMOJI_REGEX =
  /\p{Extended_Pictographic}(?:\uFE0F|\uFE0E)?(?:[\u{1F3FB}-\u{1F3FF}])?(?:\u200D(?:\p{Extended_Pictographic}|\uFE0F)(?:[\u{1F3FB}-\u{1F3FF}])?)*|\p{Regional_Indicator}{2}|[#*0-9]\uFE0F\u20E3/gu

// Fallback icon for any emoji not in the specific map
const FALLBACK_ICON = Circle

/**
 * Normalise an emoji match for map lookup: strip variation selectors and
 * keycap combining marks so e.g. "⚠️" (with U+FE0F) looks up as "⚠".
 */
function normaliseEmoji(emoji: string): string {
  return emoji.replace(/[\uFE0F\uFE0E\u20E3]/g, '')
}

/**
 * Splits a string into React nodes, replacing every emoji with an inline
 * Lucide icon. Emojis in the specific map get their mapped icon; everything
 * else gets a small generic circle.
 */
export function renderWithIcons(text: string, key?: string | number): React.ReactNode {
  const parts: Array<string | React.ReactElement> = []
  let lastIndex = 0

  // Reset stateful regex before each call
  ANY_EMOJI_REGEX.lastIndex = 0

  let match: RegExpExecArray | null
  while ((match = ANY_EMOJI_REGEX.exec(text)) !== null) {
    const emoji = match[0]
    const index = match.index

    if (index > lastIndex) {
      parts.push(text.slice(lastIndex, index))
    }

    const normalised = normaliseEmoji(emoji)
    const Icon =
      EMOJI_ICON_MAP[emoji] ?? EMOJI_ICON_MAP[normalised] ?? FALLBACK_ICON

    parts.push(
      <Icon
        key={`${key ?? ''}-emoji-${index}`}
        aria-label={emoji}
        className={
          Icon === FALLBACK_ICON
            ? 'inline-block h-[0.6em] w-[0.6em] align-middle mx-[0.15em] flex-shrink-0 opacity-30 fill-current'
            : 'inline-block h-[1em] w-[1em] align-[-0.125em] mx-[0.1em] flex-shrink-0'
        }
      />,
    )

    lastIndex = index + emoji.length
  }

  if (lastIndex < text.length) {
    parts.push(text.slice(lastIndex))
  }

  if (parts.length === 0) return text
  if (parts.length === 1 && typeof parts[0] === 'string') return parts[0]

  return <>{parts}</>
}

/**
 * Walks React children and replaces emoji strings in text nodes with icons.
 * Safe to use inside markdown component renderers.
 */
export function processChildrenWithIcons(
  children: React.ReactNode,
  keyPrefix?: string,
): React.ReactNode {
  return React.Children.map(children, (child, i) => {
    if (typeof child === 'string') {
      return renderWithIcons(child, `${keyPrefix ?? ''}-${i}`)
    }
    return child
  })
}
